version: '3'
services:
  taskdb:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: MyPassword1
      MYSQL_DATABASE: task
      MYSQL_ROOT_PASSWORD: MyPassword1
      MYSQL_TCP_PORT: 3307
    ports:
      - "3307:3307"
  taskapi:
    build: './task-backend'
    container_name: taskapi
    restart: always
    depends_on: 
      - taskdb
    environment:
      - DB_HOST=taskdb
      - DB_PORT=3307
      - DB_NAME=task
      - DB_USERNAME=root
      - DB_PASSWORD=MyPassword1
    ports: 
      - 8082:8082
  taskui:
    container_name: taskui
    build: ./task-frontend
    depends_on: 
      - taskapi
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start